[package]
name = "rust-soot"
version = "0.1.0"
authors = ["nicolelisa <nhagerma@ualberta.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
